### ISSUE TITLE
Tab columns interfere with autocomplete

### ISSUE THREAD

**Issue by PicoPlanetDev** [seanahan5000/rpw-ext#1]
Hi there! Decided to try this extension out as I liked how compatible it was with different syntaxes. Currently, I have one small issue right now that I'm not sure if it is possible to configure to resolve:

Whenever a VSCode autocomplete suggestion shows up, I would normally use the up/down arrow keys and tab to accept it. However, pressing tab with this extension active jumps to the next column. Is it possible to disable the column tab functionality when an autocomplete suggestion is available?

**Comment by seanahan5000** [comment]
Thanks for the suggestion.  I'll add a setting to turn off the column tab completely, but I haven't figured out how to selectively enable/disable it depending on context.

**Comment by seanahan5000** [comment]
I found a solution for the issue without having to turn off column tabbing completely.  Fixed in 1.1.1.

**Comment by PicoPlanetDev** [comment]
Just had a chance to test it out and it's great! Thanks so much.
